# Generated by Django 3.0 on 2019-12-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSendLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailto', models.CharField(max_length=300, verbose_name='收件人')),
                ('title', models.CharField(max_length=2000, verbose_name='邮件标题')),
                ('content', models.TextField(verbose_name='邮件内容')),
                ('send_result', models.BooleanField(default=False, verbose_name='结果')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '邮件发送日志',
                'verbose_name_plural': '邮件发送日志',
                'ordering': ['-created_time'],
            },
        ),
    ]
