# Generated by Django 3.0 on 2019-12-13 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_name', models.CharField(max_length=200, verbose_name='标题')),
                ('art_add_date', models.DateTimeField(auto_now_add=True)),
                ('art_author', models.CharField(default='', max_length=10, verbose_name='作者')),
                ('art_type', models.CharField(choices=[('流行', (('xuanhuan', '玄幻'), ('qihuan', '奇幻'), ('kehuan', '科幻'), ('wuxia', '武侠'), ('xianxia', '仙侠'), ('dushi', '都市'), ('yanqing', '言情'), ('lishi', '历史'))), ('经典', (('mingzhu', '名著'), ('shenhua', '神话'), ('xiaoshuo', '小说'), ('zhuzi', '诸子'), ('shici', '诗词'), ('shishu', '史书')))], max_length=200)),
                ('art_status', models.CharField(default='', max_length=200, verbose_name='状态')),
                ('art_introduction', models.CharField(default='', max_length=2000, verbose_name='简介')),
                ('art_name_used', models.CharField(default='', max_length=200, verbose_name='曾用名')),
                ('art_hits', models.IntegerField(default='0', verbose_name='点击量')),
                ('art_hots', models.IntegerField(default='0', verbose_name='点击量')),
                ('word_number', models.IntegerField(default=0, null=True, verbose_name='字数')),
                ('user_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['art_add_date'],
            },
        ),
        migrations.CreateModel(
            name='ArtChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=200, verbose_name='章名')),
                ('chapter_content', tinymce.models.HTMLField(verbose_name='文章内容')),
                ('chapter_add_date', models.DateTimeField(auto_now=True)),
                ('word_number', models.IntegerField(default=0, null=True, verbose_name='字数')),
                ('chapter_hits', models.IntegerField(default='0', null=True, verbose_name='点击')),
                ('chapter_hots', models.IntegerField(default='0', null=True, verbose_name='推荐')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reader.Article', verbose_name='文章')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
