# Generated by Django 3.0 on 2019-12-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_auto_20191216_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment_nums',
            field=models.IntegerField(default=0, null=True, verbose_name='评论数'),
        ),
    ]
