# Generated by Django 3.0 on 2019-12-24 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_article_comment_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='artchapter',
            name='last_mod_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间'),
        ),
    ]
