# Generated by Django 3.0 on 2019-12-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_artchapter_last_mod_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artchapter',
            name='last_mod_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='修改时间'),
        ),
    ]
