# Generated by Django 3.0 on 2020-01-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0005_auto_20191224_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='artchapter',
            name='section_name',
            field=models.CharField(max_length=200, null=True, verbose_name='部分'),
        ),
    ]
