# Generated by Django 3.0 on 2020-01-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0008_auto_20200105_1719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShiCi',
        ),
    ]
