# Generated by Django 3.0 on 2020-01-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0009_delete_shici'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名称')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='art_label',
            field=models.ManyToManyField(to='reader.Label'),
        ),
    ]
