# Generated by Django 3.0 on 2019-12-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191221_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohlaauser',
            name='avatar',
            field=models.FileField(default='/media/avatars/default.png', upload_to='avatar'),
        ),
    ]
