# Generated by Django 3.0 on 2019-12-28 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191224_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_key', models.CharField(blank=True, max_length=30, verbose_name='用户标识')),
                ('article_id', models.IntegerField(blank=True, verbose_name='书id')),
                ('chapter_id', models.IntegerField(blank=True, verbose_name='章id')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '历史记录',
                'verbose_name_plural': '历史记录',
                'ordering': ['history_key'],
                'get_latest_by': 'id',
            },
        ),
    ]
