# Generated by Django 3.0 on 2019-12-28 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_historydata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historydata',
            old_name='article_id',
            new_name='book_id',
        ),
    ]
